# Generated by Django 3.0.3 on 2020-10-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='travelimg',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='travel',
            name='type_travel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='traveltype',
            name='travel_detail',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='traveltype',
            name='travel_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='traveltype',
            name='travel_wherename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='traveluser',
            name='travel_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
